workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Create Flutter project structure
        script: |
          #!/usr/bin/env bash
          set -ex
          echo 'Backing up your files...'
          mv lib /tmp/lib_backup
          mv pubspec.yaml /tmp/pubspec_backup
          
          echo 'Cleaning directory...'
          rm -rf *
          
          echo 'Running flutter create...'
          flutter create --org com.tawasul --project-name tawasul_pro .
          
          echo 'Updating compileSdkVersion to 36...'
          sed -i '' 's/compileSdk = flutter.compileSdkVersion/compileSdk = 36/g' android/app/build.gradle.kts
          sed -i '' 's/targetSdk = flutter.targetSdkVersion/targetSdk = 36/g' android/app/build.gradle.kts
          
          echo 'Forcing compileSdk 36 for all Firebase plugins...'
          cat >> android/build.gradle.kts << 'EOF'
          
          subprojects {
              afterEvaluate {
                  if (project.plugins.hasPlugin("com.android.library")) {
                      project.extensions.configure<com.android.build.gradle.LibraryExtension> {
                          compileSdk = 36
                      }
                  }
              }
          }
          EOF
          
          echo 'Restoring your files...'
          rm -rf lib pubspec.yaml
          mv /tmp/lib_backup lib
          mv /tmp/pubspec_backup pubspec.yaml
          
          echo "Android folder created successfully"
          ls -la android
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
