name: tawasul_pro
description: تواصل PRO - دردشة وكروبات ومنشورات وستوري مع دخول Google
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4

flutter:
  uses-material-design: true
